services:
  postgres_students_db:
    image: postgres
    container_name: postgres_students_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env.test
    volumes:
      - pg_students-db:/var/lib/postgresql/data

  node_students_app:
    container_name: node_students_app
    build: ./back-end
    image: node_students_app_image
    ports:
      - 5000:5000
    depends_on:
      - postgres_students_db
    env_file:
      - back-end/.env.test

  react_students_app:
    container_name: react_students_app
    build: ./front-end
    image: react_students_app_image
    volumes:
      - build_react:/var/www/html

  nginx_students_app:
    container_name: nginx_students_app
    build: ./nginx
    image: nginx_students_app_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres_students_db
      - node_students_app
      - react_students_app

volumes:
  pg_students-db:
  build_react: