name: Deploy na AWS
on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: self-hosted
    timemeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end .env file
        uses: SpicyPizza/create-envfile@1.3
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_PORT: ${{secrets.PORT}}
          directory: back-end/
          file_name: .env
          fail_on_empt: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empt: true
      - name: Build process
        run: docker-compose build
      - name: Run app docker compose
        run: docker-compose down && docker-compose up -d
